default: &default
  example: "www.example.com"
  alipay:
    pid: '2088412481686716' # replace with your own
    secret: 'p36fbudrydlvde32agr2xpqf6m8fk3nb'
    seller_email: "aichun.sha@wohecha.cn" # your alipay acount that you used to reigister the app
    return_url: "http://wohecha.cn/transactions/done"
    notify_url: "http://wohecha.cn/transactions/notify"

production:
  <<: *default

development:
  <<: *default

test:
  <<: *default
  default_password: ''
